swagger: "2.0"
info:
  title: "Code For Denver partner finder api"
  version: "1.0"
  description: "Aggregates data on Colorado nonprofits that Code For Denver can potentially partner with on projects. Data sources are socrata api and Colorado Nonprofits."
host: "localhost:8000"
schemes:
  - "http"
securityDefinitions:
  bearerAuth:
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: Authorization  # name of the header, query parameter or cookie
security:
  - bearerAuth: []
paths:
  /login:
    post:
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            required:
              - username
              - password
            properties:
              username:
                type: "string"
              password:
                type: "string"
      responses:
        "200":
          description: "Login successful. Returns a JWT token."
  /leads:
    get:
      parameters:
        - name: page
          in: query
          type: integer
          description: Results indexed from (page - 1) * perpage up to (page * perpage) - 1 are returned.
          required: false
          default: 1
          minimum: 1
        - name: perpage
          in: query
          type: integer
          description: The number of records to return in a single request.
          required: false
          default: 100
          minimum: 1
          maximum: 1000
        - name: search
          in: query
          type: string
          description: A string to search for in lead titles and descriptions.
          required: false
        - name: tag
          in: query
          type: string
          description: Restrict returned leads to only those that have been assigned a specific tag (or label).
        - name: drop_null
          in: query
          type: boolean
          description: When true, removes fields with null values from each lead in the response.
        - name: include
          in: query
          type: string
          description: A comma separated list of fieldnames. The fields returned in each lead object will be restricted to match this list of names.
      responses:
        "200":
          description: "success"


