# name: flake8 Lint

name: flake8 Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          path: "backend"
          max-line-length: "120"
          exclude: ".git,__pycache__,venv,__init__.py"

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: cd frontend/cfd-partner-finder-frontend
      - name: Install node dependencies
        run: npm install -y
      - name: Check that the formatter was run
        run : npm run format.check
      - name: Check for linting errors
        run: npm run lint
